pipeline:
  ping:
    image: mongo:3.4.4
    commands:
      - sleep 15
      - mongo --host mongo

  install:
    image: erxes/runner:latest
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install

  linting:
    image: erxes/runner:latest
    commands:
      - yarn lint

  typescript:
    image: erxes/runner:latest
    commands:
      - yarn tsc

  testing:
    image: erxes/runner:latest
    environment:
      - TEST_MONGO_URL=mongodb://mongo/test
    commands:
      - yarn test

  build:
    image: erxes/runner:latest
    commands:
      - yarn build
      - cp .env.sample .env

  publish:
    image: plugins/docker
    repo: goharbor.erxes.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    registry: goharbor.erxes.io
    dockerfile: Dockerfile
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_BRANCH}-latest
    when:
      branch: [fix-google-cred]
      event: push
      status: success

services:
  mongo:
    image: mongo:3.4.4
    command: [--smallfiles]
